# _config.yml

title:       "Corey Zhang"
description: "Mathematician | Data Scientist<br><br>Portfolio of Mathematics & Data Science projects"

url:         "https://coreygz.github.io"
baseurl:     "/portfolio"

remote_theme: "pages-themes/merlot@v0.3.0"

plugins:
  - jekyll-feed

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
