# Site identity
title:       "Corey Zhang"
description: "Mathematician | Data Scientist<br><br>Portfolio of Mathematics & Data Science projects"

# GitHub Pages URLs
url:      "https://coreygz.github.io"
baseurl:  "/portfolio"

# Use Merlot v0.2.0 from the pages-themes repo
remote_theme: "pages-themes/merlot@v0.2.0"

# Plugins (jekyll-remote-theme is required for remote_theme to work)
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Markdown parser
markdown: kramdown

# Skip these
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
