# Site settings
title: "Corey Zhang"
email: "coreyz@udel.edu"
description: "Portfolio of Mathematics & Data Science projects"

# GitHub Pages URLs
url: "https://coreygz.github.io"   # your user site
baseurl: "/portfolio"              # your repo’s subpath

# Theme
theme: jekyll-theme-minimal          # built-in Pages theme—no extra plugins needed

# Plugins
plugins:
  - jekyll-feed

# Navigation bar
navbar:
  - title: Home
    url: /
  - title: Mathematics
    url: /math/
  - title: Data Science
    url: /data-science/

# Markdown parser
markdown: kramdown

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
