# Site settings
title: "Corey Zhang"
email: "coreyz@udel.edu"
description: "Portfolio of Mathematics & Data Science projects"

# GitHub Pages URLs
url: "https://coreygz.github.io"
baseurl: "/portfolio"

# Theme
remote_theme: "pages-themes/slate@v0.2.0"

# Global navigation links (appears in the top bar)
header-links:
  - title: Home
    url: /
  - title: Mathematics
    url: /math/
  - title: Data Science
    url: /data-science/

# Plugins
plugins:
  - jekyll-feed

# Markdown parser
markdown: kramdown

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
