# Site settings
title: "Corey Zhang"
email: "coreyz@udel.edu"
description: "Portfolio of Mathematics & Data Science projects"
baseurl: ""                                 # if your repo is a user site, leave blank
url: "https://<your-username>.github.io"    # your Pages URL

# Theme: use a GitHub Pages–hosted theme
remote_theme: "pages-themes/slate@v0.2.0"

# Plugins
plugins:
  - jekyll-feed

# Navigation bar
navbar:
  - title: Home
    url: /
  - title: Mathematics
    url: /math/
  - title: Data Science
    url: /data-science/

# Markdown parser
markdown: kramdown

# Ignore these files/folders
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
