# _config.yml

# Site identity
title:       "Corey Zhang"
description: "Mathematician | Data Scientist<br><br>Portfolio of Mathematics & Data Science projects"

# URLs
url:      "https://coreygz.github.io"   # your user site
baseurl:  "/portfolio"                  # subpath for this project

# Theme (remote_theme must be declared when overriding layouts/includes)
remote_theme: "pages-themes/merlot@v0.3.0"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Markdown parser
markdown: kramdown

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
